backend:
  name: github
  repo: definitelynotneil/neat-blog
media_folder: "src/static/img"
public_folder: "/static/img"
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
media_library:
  name: Media
collections:
  - label: "Blog"
    name: "blog"
    folder: "src/posts"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "{{ settings.author }}" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Related Posts", widget: "relation", collection: "blog", name: "related", search_fields: ['title'], value_field: "{{ slug }}" }
  - label: "Pages"
    name: "pages"
    folder: "src/pages"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yml"
        fields:
          - { label: Nav Items, name: items, widget: list, allow_add: true, collapsed: false }
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Description, name: description, widget: string }
